db:
  image: camptocamp/postgresql:pg9.5-latest
  environment:
    POSTGRES_USER: docker
    POSTGRES_PASSWORD: docker
    POSTGRES_DB: gis
    PG_SYSTEM_SHARED_BUFFERS: 256MB
    PG_SYSTEM_MAX_CONNECTIONS: 200
  volumes:
    - ./docker-osm/db:/var/lib/postgresql/data
  ports:
    - 15432:5432

mapserver:
  image: camptocamp/mapserver:latest
  ports:
    - 8081:80
  volumes:
    - ./mapserver:/etc/mapserver
  links:
    - db

geoserver:
  image: camptocamp/geoserver:2.9
  ports:
    - 8082:8080
  volumes:
    - ./geoserver:/usr/local/tomcat/webapps/ROOT/data
  links:
    - db

geoserver-jai:
  image: camptocamp/geoserver:2.9
  ports:
    - 8085:8080
  environment:
    CATALINA_OPTS: ""
  volumes:
    - ./geoserver:/usr/local/tomcat/webapps/ROOT/data
  links:
    - db

qgis3:
  image: camptocamp/qgis-server:3
  environment:
    QGIS_SERVER_LOG_LEVEL: 3
    QGIS_OPTIONS_PATH: /root/
  ports:
    - 8083:80
  volumes:
    - ./qgis:/project
    - ./qgis/QGIS:/root/QGIS
  links:
    - db

qgis2:
  image: camptocamp/qgis-server:2
  environment:
    QGIS_SERVER_LOG_LEVEL: 3
  ports:
    - 8084:80
  volumes:
    - ./qgis2:/project
  links:
    - db
